// vue/src/components/Hello.vue
<template>
  <div class="hello">
    <NativeTitle title="Hello" />
    <NativeRightBar :title="rightBarTitle" @click="rightBarClick" />
    <ul>
      <router-link to="hybrid">Hybrid</router-link>
      <li><a @click="selectImage">选择图片</a></li>
      <li><a @click="changeRightBarTitle('Forum')">Forum</a></li>
      <li><a @click="changeRightBarTitle('Chat')">Chat</a></li>
      <li><a @click="changeRightBarTitle('')">Remove</a></li>
      {{count}}
      <ImageX :src="selectedImage" style="width: 200px; margin-top: 20px;" fullScreen/>
    </ul>
  </div>
</template>

<script>
import NativeTitle from './NativeTitle'
import NativeRightBar from './NativeRightBar'
import ImageX from './ImageX'
import logo from '../assets/logo.png'

export default {
  name: 'hello',
  components: {
    NativeTitle,
    NativeRightBar,
    ImageX
  },
  data () {
    return {
      selectedImage: logo,
      count: 0,
      rightBarTitle: 'Chat',
    }
  },
  methods: {
    async selectImage () {
      let response = await this.$native.event('selectImage')
      this.selectedImage = response.image
    },
    changeRightBarTitle (title) {
      this.rightBarTitle = title
    },
    rightBarClick () {
      this.count += 1
      console.log({ count: this.count })
    }
  }
}
</script>

// react/src/Hello.js
import React, { Component } from 'react'
import './App.css'
import NativeTitle from './NativeTitle'
import NativeRightBar from './NativeRightBar'
import Image from './Image'

export default class extends Component {

  constructor(props) {
    super(props);
    this.state = {
      count: 0,
      selectedImage: 'https://facebook.github.io/react/img/logo.svg',
      rightBarTitle: 'Chat',
    }
  }

  handleClick = () => {
    this.setState((prevState) => ({
      count: prevState.count + 1
    }))
  }

  selectImage = async () => {
    let response = await window.$native.event('selectImage')
    this.setState({
      selectedImage: response.image
    })
  }

  changeRightBarTitle = (title) => {
    this.setState({
      rightBarTitle: title
    })
  }

  render() {
    return (
      <div className="App">
      <NativeTitle title="Hello" />
      <NativeRightBar title={this.state.rightBarTitle} onClick={this.handleClick}/>
      <ul>
        <li><a onClick={this.selectImage}>选择图片</a></li>
        <li><a onClick={() => this.changeRightBarTitle('Forum')}>Forum</a></li>
        <li><a onClick={() => this.changeRightBarTitle('Chat')}>Chat</a></li>
      </ul>
      {this.state.count}
      <div>
      <Image src={this.state.selectedImage} width="200" fullScreen />
      </div>
      </div>
    );
  }
}
