// vue/src/components/NativeRightBar.vue
<template>
</template>

<script>
export default {
  name: 'nativeRightBar',
  props: {
    title: String
  },
  watch: {
    'title': (newTitle) => {
      window.$native.rightBarTitle = newTitle
    }
  },
  created () {
    this.$native.rightBarTitle = this.title
    this.$native.rightBarClick = () => {
      this.$emit('click')
    }
  }
}
</script>

// react/src/NativeRightBar.js
import { Component } from 'react';
import PropTypes from 'prop-types';

export default class NativeRightBar extends Component {

  // shouldComponentUpdate(nextProps) {
  //   return nextProps.title !== this.props.title
  // }

  componentWillMount () {
    window.$native.rightBarClick = () => {
      this.props.onClick()
    }
  }

  componentWillUnmount () {
    // window.$native.rightBarClick = null
  }

  render () {
    window.$native.rightBarTitle = this.props.title || ''
    return null
  }
}

NativeRightBar.propTypes = {
  title: PropTypes.string
};
